# This file is the entry point to configure your own services.
# Files in the packages/ subdirectory configure your dependencies.

# Put parameters here that don't need to change on each machine where the app is deployed
# https://symfony.com/doc/current/best_practices.html#use-parameters-for-application-configuration
parameters:

services:
    # default configuration for services in *this* file
    _defaults:
        autowire: true      # Automatically injects dependencies in your services.
        autoconfigure: true # Automatically registers your services as commands, event subscribers, etc.

        # bind:
        #     'string $poesessid': '%env(POESESSID)%'
        #     'string $poeUsername': '%env(POE_USERNAME)%'

    _instanceof:
        DumpIt\Shared\Infrastructure\Bus\Query\QueryHandler:
            tags: 
                - { name: messenger.message_handler, bus: query.bus }
        DumpIt\Shared\Infrastructure\Bus\Command\CommandHandler:
            tags: 
                - { name: messenger.message_handler, bus: command.bus }

    # makes classes in src/ available to be used as services
    # this creates a service per class whose id is the fully-qualified class name
    DumpIt\Api\:
        resource: '../src/'
        exclude:
            - '../src/DependencyInjection/'
            - '../src/Entity/'
            - '../src/Kernel.php'
            - '../src/Behat/'

    # add more service definitions when explicit configuration is needed
    # please note that last definitions always *replace* previous ones

    DumpIt\:
        resource: '%kernel.project_dir%/vendor/dumpit/core/src/*'

    DumpIt\Api\EventListener\ExceptionListener:
        tags:
            - { name: kernel.event_listener, event: kernel.exception }

    # DumpIt\Shared\:
    #     resource: '%kernel.project_dir%/vendor/dumpit/core/src/Shared'

    # DumpIt\StashFilter\Domain\:
    #     resource: '%kernel.project_dir%/vendor/dumpit/core/src/StashFilter/Domain'

    DumpIt\Api\Fixtures\:
        resource: '%kernel.project_dir%/fixtures'

    League\Fractal\Manager:
        calls:
            - setSerializer: [ '@DumpIt\Shared\Domain\Serializer\FractalSerializer' ]
 
    DumpIt\Shared\Domain\Serializer\FractalSerializer: ~

    DumpIt\StashFilter\Domain\Filter\FilterRepositoryInterface:
        class: DumpIt\StashFilter\Infrastructure\Persistence\Filter\FilterRepository
    
    DumpIt\StashFilter\Domain\Stash\ModRepositoryInterface:
        class: DumpIt\StashFilter\Infrastructure\Persistence\Stash\ModRepository

    DumpIt\StashFilter\Domain\Stash\TabRepositoryInterface:
        class: DumpIt\StashFilter\Infrastructure\Persistence\Stash\TabRepository

    DumpIt\StashFilter\Domain\Stash\ItemRepositoryInterface:
        class: DumpIt\StashFilter\Infrastructure\Persistence\Stash\ItemRepository

    DumpIt\StashFilter\Domain\User\UserRepositoryInterface:
        class: DumpIt\StashFilter\Infrastructure\Persistence\User\UserRepository

    DumpIt\StashFilter\Domain\Stash\LeagueRepositoryInterface:
        class: DumpIt\StashFilter\Infrastructure\Persistence\Stash\LeagueRepository