version: "3.8"

services:
  nginx:
    build: docker/nginx
    ports:
      - "80:80"
    volumes:
      - ./:/var/www/dumpit
    networks:
      - dumpit

  dumpit:
    build: docker/php-fpm
    environment:
      DATABASE_HOST: postgres
      DATABASE_USER: postgres
      DATABASE_PASSWORD: password
    volumes:
      - ./:/var/www/dumpit
    networks:
      - dumpit
    extra_hosts:
      - "host.docker.internal:host-gateway"

  postgres:
    image: postgres:15-alpine
    environment:
      - POSTGRES_DB=dumpit
      - POSTGRES_PASSWORD=password
      - POSTGRES_USER=postgres
    ports:
      - "5432:5432"
    volumes:
      - db_data:/docker-entrypoint-initdb.d
    networks:
      - dumpit

networks:
  dumpit:
    driver: bridge
    
volumes:
  db_data:
