doctrine:
    dbal:
        url: '%env(resolve:DATABASE_URL)%'
        driver: 'pdo_pgsql'
    orm:
        auto_generate_proxy_classes: true
        naming_strategy: doctrine.orm.naming_strategy.default
        auto_mapping: true
        mappings:
            DumpIt:
                is_bundle: false
                type: attribute
                dir: '%kernel.project_dir%/vendor/dumpit/core/src'
                prefix: 'DumpIt'
                alias: DumpIt
